default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: pwa_demo_dev

test:
  <<: *default
  database: pwa_demo_test

production:
  <<: *default
  database: pwa_demo_production
